In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0 ,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_tow_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(tensor_tow_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [[[1,2,3],
      [4,5,6]],

     [[7,8,9],
      [10,11,12]]],


    [[[13,14,15],
      [16,17,18]],

     [[19,20,21],
      [22,23,24]]],
])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]], shape=(2, 2, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [ ]:
convert_to_tensor = tf.convert_to_tensor(np_array)
print(convert_to_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(num_rows=5, num_columns=3, batch_shape=[2,3], dtype=tf.float32)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 3, 5, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [2, 3,3,4], 6, name=None
)
print(fill_tensor)

tf.Tensor(
[[[[6 6 6 6]
   [6 6 6 6]
   [6 6 6 6]]

  [[6 6 6 6]
   [6 6 6 6]
   [6 6 6 6]]

  [[6 6 6 6]
   [6 6 6 6]
   [6 6 6 6]]]


 [[[6 6 6 6]
   [6 6 6 6]
   [6 6 6 6]]

  [[6 6 6 6]
   [6 6 6 6]
   [6 6 6 6]]

  [[6 6 6 6]
   [6 6 6 6]
   [6 6 6 6]]]], shape=(2, 3, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones([2,3,4], dtype=tf.float32)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]], shape=(2, 3, 3, 4), dtype=int32)


In [ ]:
random_tensor = tf.random.normal(
    [3,3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[[ 0.24371177 -0.8263582   1.5700436 ]
  [ 1.0016142   0.8229646  -0.58784395]
  [-1.2464437   0.7350537   0.11816662]]

 [[ 0.8111171  -2.368228   -0.9936989 ]
  [-0.9004409   0.31636778  0.5310337 ]
  [ 1.765938   -1.228089    0.8036311 ]]

 [[ 0.05034524 -0.03419123  0.44891137]
  [-0.3062004   1.4231464   0.12296418]
  [-0.9527665  -1.1701031  -1.2492363 ]]], shape=(3, 3, 3), dtype=float32)


In [23]:
uniform_tensor = tf.random.uniform(
    [3,3],
    minval=0,
    maxval=100,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(uniform_tensor)


tf.Tensor(
[[87.41963  33.238636 42.087173]
 [82.0144   21.518051 27.006102]
 [77.751564 18.765736 24.921083]], shape=(3, 3), dtype=float32)


In [27]:
tensor_indexed = tf.constant([1,2,3,4,5,6,7])
print(tensor_indexed[-1])

tf.Tensor(7, shape=(), dtype=int32)


In [38]:
print(tensor_indexed[0:])
print(tensor_indexed[:7:2])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)


In [40]:
tensor_indexed_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(tensor_indexed_two_d)


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [41]:
print(tensor_indexed_two_d[0,2])

tf.Tensor(3, shape=(), dtype=int32)


In [53]:
print(tensor_indexed_two_d[:-1,1:])

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


In [55]:
print(tf.abs(x=tf.constant(-4.0)))

tf.Tensor(4.0, shape=(), dtype=float32)


In [62]:
a = tf.constant([1,2,3,4])
b = tf.constant([5,6,7,8])

tf.einsum('i,i ->', a,b)
tf.einsum('i,i -> i', a, b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [64]:
c = tf.einsum('i,j -> ij', a, b)
print(c)

tf.Tensor(
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]], shape=(4, 4), dtype=int32)


In [61]:
tf.einsum('ij -> ji', c)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32]], dtype=int32)>

In [66]:
 tf.expand_dims(c, axis=-1)

<tf.Tensor: shape=(4, 4, 1), dtype=int32, numpy=
array([[[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[10],
        [12],
        [14],
        [16]],

       [[15],
        [18],
        [21],
        [24]],

       [[20],
        [24],
        [28],
        [32]]], dtype=int32)>